apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: powerflex
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - matrix:
              generators:
                - clusters:
                    selector:
                      matchExpressions:
                        - key: type
                          operator: Exists
                - git:
                    repoURL: https://github.com/siderolabs/powerflex-argocd-poc.git
                    revision: HEAD
                    files:
                      - path: cluster_types/{{ index .metadata.labels "type" }}.yaml
          - list:
              elements: []
              elementsYaml: '{{ .applications | toJson }}'
  template:
    metadata:
      name: '{{ .app }}'
    spec:
      project: '{{ .project | default "default" }}'
      source:
        repoURL: '{{ .repoURL | default "https://github.com/siderolabs/powerflex-argocd-poc.git" }}'
        targetRevision: '{{ .version | default "HEAD" }}'
        path: '{{ .dir | default (printf "applications/%s" .app) }}'
      destination:
        server: '{{ .server | default "https://kubernetes.default.svc" }}'
        namespace: '{{ .namespace | default .app }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
